[footer]
messages = [
    "Building the tools for a better tomorrow!",
    # haddaway
    "What is love? Baby don't hurt me - don't hurt me, no more",
    # portal 2
    "Science isn't about WHY, it's about WHY NOT!",
    "Space. Space. I'm in space. SPAAAAAAACE!",
    # cinderella
    "Even miracles take a little time.",
    "Just because it's what's done, doesn't mean it's what should be done.",
    # alice in wonderland
    "I give myself very good advice, but I very seldom follow it.",
    # the incredibles
    "I never look back, darling! It distracts me from the now.",
    # finding nemo
    "just keep swimming, just keep swimming...",
    # oregon trail
    "You have died of dysentery.",
    # duke nukem 3d
    "It's time to kick ass and chew bubblegum... and I'm all outta gum.",
    # star fox 64
    "Do a barrel roll!",
    # legend of zelda
    "Itâ€™s dangerous to go alone, take this.",
    # super mario bros
    "Thank you Mario! But our Princess is in another castle!",
    # diablo II
    "Stay awhile, and listen!",
    # ocarina of time
    "Hey! Listen!",
]

[slack]
help_message="""
Help is on the way!

`@Blossom block <username>`: block and unblock user.
`@Blossom check <url>`: Create a new transcription check for a given Reddit URL.
`@Blossom checkstats <username>`: Get the stats about the checks the given mode has done.
`@Blossom help`: Render this message.
`@Blossom info`: Get general server information.
`@Blossom info <username>`: Get information about a user.
`@Blossom migrate <source> <target>`: Creates a request to migrate the gamma count of the source to the target. Needs verification.
`@Blossom reset <username>`: Toggle CoC status of user.
`@Blossom unwatch <username>`: Reset check percentage.
`@Blossom warnings <username>`: Get the warnings of a given user.
`@Blossom watch <username> <percentage>`, where `<percentage>` is a number between 0 and 100: Overwrite check percentage.
`@Blossom watchlist <sorting>`, where `<sorting>` is either "percentage" (default) or "alphabetical": List all overwritten check percentages.
`@Blossom watchstatus <username>`: Get the check percentage for a user.
"""

server_summary="""
Here's a status update on everything!

```
{0}
```
"""

github_sponsor_update="{0} GitHub Sponsors: [{1}] - {2} | {3} {0}"

[slack.errors]
unknown_request="Sorry, I'm not sure what you're asking for."
message_parse_error="Sorry, something went wrong and I couldn't parse your message."
empty_message_error="Sorry, I wasn't able to get text out of that. Try again."
too_many_params="Too many parameters; please try again."
missing_username="I don't see a username in your request -- make sure you're formatting your request as \"@Blossom {action} {argument}\". Example: \"@Blossom dadjoke @itsthejoker\""
missing_multiple_usernames="This command uses multiple usernames -- make sure you're formatting your command as \"@Blossom {action} {argument} {argument} ...\"."
unknown_username="Sorry, I couldn't find a user with the name `u/{username}`. Please check your spelling."
unknown_payload="Received unknown payload from Slack with key I don't recognize. Unknown key: {}"

[slack.block]
success="User '{0}' blocked."
success_undo="User '{0}' unblocked."

[slack.reset_coc]
success="Code of Conduct acceptance revoked for user '{0}'."
success_undo="Code of Conduct acceptance approved for user '{0}'."

[slack.watch]
invalid_percentage="{percentage} is an invalid percentage. Please provide a number between 0 and 100, such as '50%' or '75'."
percentage_too_low="Sorry, you can't set the percentage lower than the automatic check percentage for this user ({auto_percentage:.1%})!"
success="The transcriptions of {user} now have a {percentage:.0%} chance to be checked.\nPreviously: {previous}.\nUse `unwatch {user}` to undo this."

[slack.unwatch]
success="The chance to check transcriptions of {user} is now determined automatically."

[slack.watchstatus]
success="Watch status for {user}: {status}"

[slack.dadjoke]
message = "Hey {0}! {1}"
fallback_joke = "Did you know that fortune tellers make their tents purple? They believe the color has mythical properties. It allows them to tell the fuschia."

[slack.check]
success="Generated <{check_url}|a check> for <{tr_url}|this transcription> by u/{username}!"
already_checked="There's already <{check_url}|a check> for <{tr_url}|this transcription> by u/{username}!"
failed_to_send="Sorry, there was a problem sending the check to Slack!"
no_url="You need to provide a Reddit URL to generate a check for! Use `@Blossom check <url>`."
invalid_url="Sorry, `{url}` is not a valid Reddit URL. Please provide a Reddit link to a ToR post, partner post or transcription."
no_submission="Sorry, I couldn't find a submission for the URL `{url}`!"
no_transcription="<{tor_url}|The post> does not have a transcription yet!"

[slack.warnings]
warning_entry="- {date} on {source} (<{check_url}|check> | <{tr_url}|transcription>)"
warnings="u/{username} has *{count} warning(s)*:\n\n{warning_list}"
no_warnings="u/{username} does not have a warning yet!"
